version: "3.5"

services:
  nginx:
    image: nginx:latest
    container_name: mnginx
    ports:
      - "80:80"
      - "20022:20022"
    volumes:
      - ../tm_app/:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ~/.ssh:/root/.ssh:ro
    networks:
      - manager
  php:
    build:
      context: ./php
    container_name: mphp
    environment:
      XDEBUG_CONFIG: "remote_host=172.31.0.1 client_port=9000 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=manager.docker"
    volumes:
      - ../tm_app/:/var/www/
      - ./.bash_history:/root/.bash_history
      - ./php/php.ini:/usr/local/etc/php/php.ini-development
    networks:
      - manager
  mysql:
    image: mysql:8.0
    container_name: mmysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - manager

networks:
  manager:
    driver: bridge